# Generated by Django 5.0.2 on 2024-03-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='new_csv',
            field=models.FileField(blank=True, null=True, upload_to='new_csv_file/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='old_csv',
            field=models.FileField(blank=True, null=True, upload_to='old_csv_file/'),
        ),
    ]
