# Generated by Django 5.0.2 on 2024-03-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Technician', 'Technician'), ('User', 'User')], default='User', max_length=20),
        ),
    ]
