# Generated by Django 5.0.2 on 2024-03-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('None', 'None')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Technician', 'Technician'), ('User', 'User'), ('None', 'None')], default='User', max_length=20),
        ),
    ]
