# Generated by Django 5.0.2 on 2024-03-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='id',
            field=models.CharField(default='54', max_length=50, primary_key=True, serialize=False),
        ),
    ]
