# Generated by Django 5.0.2 on 2024-03-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_gender_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Technical', 'Technical'), ('User', 'User'), ('None', 'None')], default='User', max_length=20),
        ),
    ]
