# Generated by Django 5.0.2 on 2024-03-02 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('lattitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=255)),
                ('user_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedAddress',
            fields=[
                ('saved_address_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('lattitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=255)),
                ('user_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
