# Generated by Django 5.0.2 on 2024-03-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_location_savedaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other'), ('none', 'none')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'doctor'), ('technical', 'technical'), ('user', 'user'), ('none', 'none')], default='user', max_length=20),
        ),
    ]
