# Generated by Django 5.0.2 on 2024-03-02 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_user_gender_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('contact', models.CharField(blank=True, max_length=13)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('date', models.DateField()),
                ('slot_time', models.TimeField()),
                ('relation', models.CharField(choices=[('1', 'Self'), ('2', 'Father'), ('3', 'Mother'), ('4', 'Wife'), ('5', 'Husband'), ('6', 'Son'), ('7', 'Daughter'), ('8', 'Brother')], default='1', max_length=20)),
                ('blood_group', models.CharField(choices=[('1', 'A+'), ('2', 'A-'), ('3', 'B+'), ('4', 'B-'), ('5', 'O+'), ('6', 'O-')], default='Male', max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='1', max_length=20)),
                ('predicted_file', models.URLField(blank=True)),
                ('symptoms', models.TextField()),
                ('doctor', models.CharField(blank=True, max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('consultation', models.CharField(choices=[('online', 'online'), ('offline', 'offline')], default='offline', max_length=20)),
                ('appointment_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
