# Generated by Django 5.0.2 on 2024-03-02 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_countrytechnical_districttechnical_statetechnical_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('symptoms', models.TextField(default='NULL')),
                ('suggestion_test', models.TextField(default='NULL')),
                ('advice', models.TextField(default='NULL')),
                ('rx', models.TextField(default='NULL')),
                ('patient_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.appointment')),
            ],
        ),
    ]
