# Generated by Django 5.0.2 on 2024-03-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='meet_link',
            field=models.CharField(blank=True, default='none', max_length=255),
        ),
    ]
